//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointSwitch.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PointSwitch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 批量重命名 的本地化字符串。
        /// </summary>
        internal static string Batch_Rename {
            get {
                return ResourceManager.GetString("Batch_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Rename 的本地化字符串。
        /// </summary>
        internal static string Batch_Rename_en {
            get {
                return ResourceManager.GetString("Batch_Rename_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空目录 的本地化字符串。
        /// </summary>
        internal static string Clear_directory {
            get {
                return ResourceManager.GetString("Clear_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Folder 的本地化字符串。
        /// </summary>
        internal static string Clear_directory_en {
            get {
                return ResourceManager.GetString("Clear_directory_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增量添加 的本地化字符串。
        /// </summary>
        internal static string incremental_addition {
            get {
                return ResourceManager.GetString("incremental_addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Addition 的本地化字符串。
        /// </summary>
        internal static string incremental_addition_en {
            get {
                return ResourceManager.GetString("incremental_addition_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹不存在。 的本地化字符串。
        /// </summary>
        internal static string info_Dont_exist {
            get {
                return ResourceManager.GetString("info_Dont_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder doesn&apos;t exist. 的本地化字符串。
        /// </summary>
        internal static string info_Dont_exist_en {
            get {
                return ResourceManager.GetString("info_Dont_exist_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有权限访问文件夹。 的本地化字符串。
        /// </summary>
        internal static string info_Dont_permission {
            get {
                return ResourceManager.GetString("info_Dont_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have permission to access the folder. 的本地化字符串。
        /// </summary>
        internal static string info_Dont_permission_en {
            get {
                return ResourceManager.GetString("info_Dont_permission_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $&quot;从INI文件加载配置信息时发生错误：{ex.Message}&quot; 的本地化字符串。
        /// </summary>
        internal static string info_INI_error {
            get {
                return ResourceManager.GetString("info_INI_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $&quot;An error occurred while loading configuration information from the INI file: {ex.Message}“ 的本地化字符串。
        /// </summary>
        internal static string info_INI_error_en {
            get {
                return ResourceManager.GetString("info_INI_error_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生IO错误。 的本地化字符串。
        /// </summary>
        internal static string info_IO_error {
            get {
                return ResourceManager.GetString("info_IO_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO error occurred. 的本地化字符串。
        /// </summary>
        internal static string info_IO_error_en {
            get {
                return ResourceManager.GetString("info_IO_error_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $&quot;发生IO错误。\n\n目录可能有同名文件:{sourceFolderPath}\n\n可使用重命名功能修改“ 的本地化字符串。
        /// </summary>
        internal static string info_IO_samefile {
            get {
                return ResourceManager.GetString("info_IO_samefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $&quot;IO error occurred.\n\nThere may be files with the same name in the folder: {sourceFolderPath}\n\nYou can use the rename function to modify them.” 的本地化字符串。
        /// </summary>
        internal static string info_IO_samefile_en {
            get {
                return ResourceManager.GetString("info_IO_samefile_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $&quot;成功复制 {copiedFilesCount} 个文件。\n目标文件夹内共有 {targetFilesCount} 个文件。“ 的本地化字符串。
        /// </summary>
        internal static string info_OK_copy {
            get {
                return ResourceManager.GetString("info_OK_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $&quot;Successfully copied {copiedFilesCount} files.\nThere are {targetFilesCount} files in the target folder.” 的本地化字符串。
        /// </summary>
        internal static string info_OK_copy_en {
            get {
                return ResourceManager.GetString("info_OK_copy_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $&quot;已成功替换 {replacedFilesCount} 个文件。” 的本地化字符串。
        /// </summary>
        internal static string info_OK_replaced {
            get {
                return ResourceManager.GetString("info_OK_replaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully replaced {replacedFilesCount} files. 的本地化字符串。
        /// </summary>
        internal static string info_OK_replaced_en {
            get {
                return ResourceManager.GetString("info_OK_replaced_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $&quot;重命名成功{count}个文件&quot; 的本地化字符串。
        /// </summary>
        internal static string info_rename {
            get {
                return ResourceManager.GetString("info_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $&quot;Successfully rename {count} files.” 的本地化字符串。
        /// </summary>
        internal static string info_rename_en {
            get {
                return ResourceManager.GetString("info_rename_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一个文件夹。 的本地化字符串。
        /// </summary>
        internal static string info_select_folder {
            get {
                return ResourceManager.GetString("info_select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a folder first. 的本地化字符串。
        /// </summary>
        internal static string info_select_folder_en {
            get {
                return ResourceManager.GetString("info_select_folder_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入一个有效的目录路径。 的本地化字符串。
        /// </summary>
        internal static string info_valid_folder {
            get {
                return ResourceManager.GetString("info_valid_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid folder path. 的本地化字符串。
        /// </summary>
        internal static string info_valid_folder_en {
            get {
                return ResourceManager.GetString("info_valid_folder_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string Language_Chinese {
            get {
                return ResourceManager.GetString("Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开目录 的本地化字符串。
        /// </summary>
        internal static string open_folder {
            get {
                return ResourceManager.GetString("open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Folder 的本地化字符串。
        /// </summary>
        internal static string open_folder_en {
            get {
                return ResourceManager.GetString("open_folder_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位目录 的本地化字符串。
        /// </summary>
        internal static string point_Folder {
            get {
                return ResourceManager.GetString("point Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Point Folder 的本地化字符串。
        /// </summary>
        internal static string point_Folder_en {
            get {
                return ResourceManager.GetString("point_Folder_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位切换器 的本地化字符串。
        /// </summary>
        internal static string pointswitch {
            get {
                return ResourceManager.GetString("pointswitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PointSwitch 的本地化字符串。
        /// </summary>
        internal static string pointswitch_en {
            get {
                return ResourceManager.GetString("pointswitch_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新加载 的本地化字符串。
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload 的本地化字符串。
        /// </summary>
        internal static string Reload_en {
            get {
                return ResourceManager.GetString("Reload_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一键替换 的本地化字符串。
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        internal static string Replace_en {
            get {
                return ResourceManager.GetString("Replace_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标目录 的本地化字符串。
        /// </summary>
        internal static string teleports_Folder {
            get {
                return ResourceManager.GetString("teleports Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teleports Folder 的本地化字符串。
        /// </summary>
        internal static string teleports_Folder_en {
            get {
                return ResourceManager.GetString("teleports_Folder_en", resourceCulture);
            }
        }
    }
}
